[ibkr]
host = "127.0.0.1"
port = 7497
client_id = 1
paper_trading = true

[strategy]
ema_periods = [
    9,
    21,
    50,
]
noise_filter_threshold = 0.5
gap_threshold = 0.02
reversal_confirmation_periods = 3
min_confidence_threshold = 0.6
lookback_periods = 100

[enhanced_strategy]
strategy_type = "Combined"

[enhanced_strategy.indicators]
rsi_enabled = true
rsi_period = 14
rsi_weight = 1.0
macd_enabled = true
macd_fast_period = 12
macd_slow_period = 26
macd_signal_period = 9
macd_weight = 1.0
bollinger_enabled = true
bollinger_period = 20
bollinger_std_dev = 2.0
bollinger_weight = 0.8
stochastic_enabled = false
stochastic_k_period = 14
stochastic_d_period = 3
stochastic_weight = 0.7
williams_r_enabled = false
williams_r_period = 14
williams_r_weight = 0.6
cci_enabled = false
cci_period = 20
cci_weight = 0.7
atr_enabled = true
atr_period = 14
atr_weight = 0.5
volume_enabled = true
volume_period = 20
volume_weight = 0.6
support_resistance_enabled = true
support_resistance_lookback = 50
support_resistance_weight = 0.8

[enhanced_strategy.signal_weights]
trend_following = 1.0
mean_reversion = 0.8
momentum = 0.9
volume_confirmation = 0.6
volatility_adjustment = 0.5

[enhanced_strategy.risk_parameters]
min_confidence_threshold = 0.6
max_position_size = 0.1
stop_loss_pct = 0.05
take_profit_pct = 0.1
max_drawdown_pct = 0.15
correlation_threshold = 0.7

[enhanced_strategy.backtesting]
enabled = false
initial_capital = 100000.0
commission_per_trade = 1.0
slippage_pct = 0.001
benchmark_symbol = "SPY"

[historical_backtesting]
enabled = true
symbols = ["AAPL", "MSFT", "GOOGL", "TSLA", "NVDA"]
start_date = "2023-01-01"
end_date = "2023-12-31"
bar_size = "1 day"  # "1 day", "1 hour", "30 mins", "15 mins", "5 mins", "1 min"
initial_capital = 100000.0
commission_per_trade = 1.0
slippage_pct = 0.001  # 0.1% slippage
what_to_show = "TRADES"  # "TRADES", "MIDPOINT", "BID", "ASK"
use_rth = true  # Regular Trading Hours only
benchmark_symbol = "SPY"
save_results = true
output_directory = "backtest_results"
generate_charts = false
detailed_logging = false

[trading]
symbols = [
    "AAPL",
    "MSFT",
    "GOOGL",
    "TSLA",
]
timeframe = "1min"
max_positions = 5
position_size_pct = 0.1

[trading.trading_hours]
start = "09:30"
end = "16:00"
timezone = "US/Eastern"

[risk]
max_daily_loss_pct = 0.02
max_position_size_pct = 0.15
stop_loss_pct = 0.05
take_profit_pct = 0.1
max_correlation = 0.7
var_limit = 0.03
